#!/bin/bash

set -e

# Variables for console color
RED='\033[0;31m'
NC='\033[0m'

print_error() {
  echo -e "${RED}[ERROR]${NC} $1" >&2
}

COMMIT_MSG="$1"
REGEX='(feat|fix|chore|perf|test){1}\([a-z-\/]+\)[!]?(:){1}'

if [[ ! "$COMMIT_MSG" =~ (feat|fix|chore|perf|test){1}\([a-z\/\-]+\)[!]?(:){1} ]]; then
  print_error "commit message does not match the regex"
  exit 1
fi