#!/bin/bash
set -e

# Variables for console color
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_error() {
  echo -e "${RED}[ERROR]${NC} $1" >&2
}
print_info() {
  echo -e "${YELLOW}$1${NC}"
}
print_success() {
  echo -e "${GREEN}$1${NC}"
}

print_info "Running test for changed files"



if $(npx craco test --onlyChanged) ;then
  print_error "Test failed"
  exit 1
fi

print_success "Test successful"