#!/bin/bash
set -e

# Variables for console color
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

allowedYn=("y" "n")

print_error() {
  echo -e "${RED}[ERROR]${NC} $1" >&2
}
print_info() {
  echo -e "${YELLOW}$1${NC}"
}
print_success() {
  echo -e "${GREEN}$1${NC}"
}

# assigns standard input to the keyboard
exec < /dev/tty

regex="((.ts){1}(x)?)$" # Matches any file with the extension .ts, .tsx

# shellcheck disable=SC2076
while [[ ! " ${allowedYn[*],,} " =~ " ${fixLint,,} " ]]; do
    read -r -p $'Immediately fix linting errors? (Y/n)\n' fixLint
done

for file in $(git diff --cached --name-only HEAD); do
    if [[ "$file" =~ $regex ]];then
        print_info "Running eslint for $file"

        if [ "n" = "${fixLint,,}" ]; then
          npx eslint "$file"
        else
          npx eslint "$file" --fix
        fi

    fi
done